"""Migrate a research directory to the current v4 layout.

Handles two upgrade paths in one pass:
  1) v1 → v4: flat raw `.md` files (and GitHub repo subdirs) live at the root of
     the research dir. Move them into `raw/` and `wiki/repos/` and repoint
     `uri_full` / `uri_highlights` in `index.yaml`.
  2) v3 → v4: files are nested under a `memory/` subfolder (an older wrapper).
     Hoist everything one level up so the canonical files (`index.yaml`,
     `index.md`, `log.md`, `raw/`, `wiki/`) sit directly under the research dir.

V1 (legacy):
  <research_dir>/
    index.yaml
    <source-slug>.md         # raw source files at root
    <repo-name>/             # GitHub repo subfolders at root (ARCHITECTURE.md + module docs)

V3 (legacy with wrapper):
  <research_dir>/
    memory/
      index.yaml
      raw/<source-slug>.md
      raw/assets/
      wiki/

V4 (current target):
  <research_dir>/
    README.md                # autogenerated signpost
    index.yaml               # canonical index
    index.md                 # autogenerated from index.yaml
    log.md                   # append-only, with a `migrate` entry
    raw/<source-slug>.md
    raw/assets/
    wiki/                    # synthesis pages

Behavior:
  - Idempotent: if the directory already matches v4 (raw/ + wiki/ at root), only
    refreshes README/log scaffolding and regenerates index.md.
  - For v3 dirs, refuses to clobber a v4 file at the destination — bails with a
    clear error if both `<research_dir>/index.yaml` and
    `<research_dir>/memory/index.yaml` exist.
  - Repoints `uri_full` and `uri_highlights` paths under `raw/` (or
    `wiki/repos/` for GitHub repos) for v1 dirs.
  - Creates README.md and log.md if missing.
  - Appends a `## [YYYY-MM-DD] migrate | layout vX → v4` entry to log.md.
  - Regenerates index.md via build_index_md.py.

Usage:
  uv run python scripts/migrate_layout.py --research-dir /path/to/research-<slug>
  uv run python scripts/migrate_layout.py --research-dir /path/to/research-<slug> --dry-run

Output: a JSON summary on stdout describing the detected source layout, what
was moved, what was skipped, and any path updates.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
BUILD_INDEX_MD = SCRIPT_DIR / "build_index_md.py"

README_TEMPLATE = """# Research Directory

This directory is a research dir produced by `/research`.

- `index.yaml` — canonical, machine-readable index of sources
- `index.md` — Obsidian-readable view of the index (AUTOGENERATED, do not edit)
- `log.md` — append-only chronological record of operations
- `raw/` — immutable source copies (and `raw/assets/` for images + original PDFs)
- `wiki/` — LLM-maintained synthesis (overview, synthesis, entities, concepts, comparisons, questions, repos, renders)

Operate on this directory through the research skills (`/research`, `/research-lint`, `/research-distill`, `/research-promote`, `/research-render`). Do not hand-edit `index.md`.
"""


def detect_layout(research_dir: Path) -> str:
    """Return one of: "v4", "v3", "v1"."""
    if (research_dir / "memory").is_dir() and (research_dir / "memory" / "index.yaml").is_file():
        return "v3"
    if (research_dir / "raw").is_dir() and (research_dir / "wiki").is_dir():
        return "v4"
    if (research_dir / "index.yaml").is_file():
        return "v1"
    raise SystemExit(f"could not detect layout for {research_dir}: no index.yaml at root and no memory/ wrapper")


def find_v1_files(research_dir: Path) -> tuple[list[Path], list[Path]]:
    """Return (markdown files at root, repo dirs at root) excluding system files."""
    md_files: list[Path] = []
    repo_dirs: list[Path] = []
    skip_files = {"index.yaml", "index.md", "README.md", "log.md", "CONVENTIONS.md", "state.md"}
    skip_dirs = {"raw", "wiki", "memory", ".github-cache"}

    for entry in research_dir.iterdir():
        if entry.name.startswith("."):
            continue
        if entry.is_file() and entry.suffix == ".md" and entry.name not in skip_files:
            md_files.append(entry)
        elif entry.is_dir() and entry.name not in skip_dirs:
            # Heuristic: a v1 GitHub repo folder contains ARCHITECTURE.md.
            if (entry / "ARCHITECTURE.md").is_file():
                repo_dirs.append(entry)

    md_files.sort()
    repo_dirs.sort()
    return md_files, repo_dirs


def repoint_uri(value: str | None, github_repo_slugs: set[str] | None = None) -> tuple[str | None, bool]:
    """Prepend 'raw/' (or 'wiki/repos/' for GitHub) to a uri_full/uri_highlights value."""
    if value is None:
        return None, False
    if value.startswith("raw/") or value.startswith("wiki/") or value.startswith("/"):
        return value, False
    if value.startswith("./"):
        value = value[2:]

    if github_repo_slugs:
        first_segment = value.split("/", 1)[0]
        if first_segment in github_repo_slugs:
            return f"wiki/repos/{value}", True

    return f"raw/{value}", True


def migrate_index_yaml(index_yaml_path: Path, github_repo_slugs: set[str], dry_run: bool) -> dict[str, Any]:
    doc = yaml.safe_load(index_yaml_path.read_text()) or {}
    sources = doc.get("sources") or []
    repointed = 0
    for src in sources:
        for field in ("uri_full", "uri_highlights"):
            new_val, changed = repoint_uri(src.get(field), github_repo_slugs=github_repo_slugs)
            if changed:
                src[field] = new_val
                repointed += 1
    if repointed and not dry_run:
        index_yaml_path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=1000))
    return {"repointed_uri_count": repointed, "total_sources": len(sources)}


def append_log_entry(log_path: Path, header: str, entry_body: list[str]) -> None:
    today = date.today().isoformat()
    block = [f"## [{today}] migrate | {header}", ""]
    block.extend(entry_body)
    block.append("")
    if log_path.exists():
        existing = log_path.read_text()
        if not existing.endswith("\n"):
            existing += "\n"
        log_path.write_text(existing + "\n".join(block) + "\n")
    else:
        log_path.write_text("# Log\n\n" + "\n".join(block) + "\n")


def regenerate_index_md(research_dir: Path) -> str:
    if not BUILD_INDEX_MD.is_file():
        return f"build_index_md.py not found at {BUILD_INDEX_MD}; skipping index.md regeneration"
    result = subprocess.run(
        [sys.executable, str(BUILD_INDEX_MD), "--research-dir", str(research_dir)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return f"build_index_md.py failed: {result.stderr.strip()}"
    return result.stdout.strip()


def migrate_v3_to_v4(research_dir: Path, dry_run: bool, summary: dict[str, Any]) -> None:
    """Hoist <research_dir>/memory/* up to <research_dir>/*."""
    inner = research_dir / "memory"
    if not inner.is_dir():
        raise SystemExit(f"v3 migration expected {inner} to exist")

    # Refuse to clobber: if any inner entry already exists at the destination, bail.
    conflicts: list[str] = []
    for entry in inner.iterdir():
        dest = research_dir / entry.name
        if dest.exists():
            conflicts.append(entry.name)
    if conflicts:
        raise SystemExit(
            f"v3→v4 migration aborted: destination already has {conflicts} alongside memory/. Resolve manually before re-running."
        )

    moved: list[dict[str, str]] = []
    for entry in sorted(inner.iterdir()):
        target = research_dir / entry.name
        moved.append({"from": str(entry), "to": str(target)})
        if not dry_run:
            shutil.move(str(entry), str(target))

    summary["hoisted_from_memory"] = moved

    # Remove the now-empty memory/ wrapper.
    if not dry_run:
        try:
            inner.rmdir()
            summary["removed_memory_wrapper"] = True
        except OSError as exc:
            summary["removed_memory_wrapper"] = False
            summary["memory_wrapper_remove_error"] = str(exc)


def migrate_v1_to_v4(research_dir: Path, dry_run: bool, summary: dict[str, Any]) -> None:
    """Move flat .md files into raw/ and repo dirs into wiki/repos/."""
    md_files, repo_dirs = find_v1_files(research_dir)

    raw_dir = research_dir / "raw"
    wiki_dir = research_dir / "wiki"
    assets_dir = raw_dir / "assets"
    wiki_repos_dir = wiki_dir / "repos"

    if not dry_run:
        raw_dir.mkdir(exist_ok=True)
        wiki_dir.mkdir(exist_ok=True)
        assets_dir.mkdir(exist_ok=True)
        wiki_repos_dir.mkdir(exist_ok=True)

    moved_files: list[dict[str, str]] = []
    for f in md_files:
        target = raw_dir / f.name
        moved_files.append({"from": str(f), "to": str(target)})
        if not dry_run:
            shutil.move(str(f), str(target))

    moved_repo_dirs: list[dict[str, str]] = []
    for d in repo_dirs:
        target = wiki_repos_dir / d.name
        moved_repo_dirs.append({"from": str(d), "to": str(target)})
        if not dry_run:
            shutil.move(str(d), str(target))

    summary["moved_files"] = moved_files
    summary["moved_repo_dirs"] = moved_repo_dirs

    github_repo_slugs = {d.name for d in repo_dirs}
    index_yaml_path = research_dir / "index.yaml"
    summary["yaml"] = migrate_index_yaml(index_yaml_path, github_repo_slugs=github_repo_slugs, dry_run=dry_run)


def ensure_v4_scaffolding(research_dir: Path, dry_run: bool, summary: dict[str, Any]) -> None:
    """Create README/log/raw/wiki/assets if missing. Idempotent."""
    raw_dir = research_dir / "raw"
    wiki_dir = research_dir / "wiki"
    assets_dir = raw_dir / "assets"

    if not dry_run:
        raw_dir.mkdir(exist_ok=True)
        wiki_dir.mkdir(exist_ok=True)
        assets_dir.mkdir(exist_ok=True)

    readme_path = research_dir / "README.md"
    if not readme_path.is_file():
        summary.setdefault("created", []).append(str(readme_path))
        if not dry_run:
            readme_path.write_text(README_TEMPLATE)


def migrate(research_dir: Path, dry_run: bool) -> dict[str, Any]:
    if not research_dir.is_dir():
        raise SystemExit(f"research dir does not exist: {research_dir}")

    layout = detect_layout(research_dir)

    summary: dict[str, Any] = {
        "research_dir": str(research_dir),
        "dry_run": dry_run,
        "detected_layout": layout,
        "target_layout": "v4",
        "created": [],
        "index_md": "",
    }

    if layout == "v4":
        summary["already_migrated"] = True
        ensure_v4_scaffolding(research_dir, dry_run, summary)
    elif layout == "v3":
        migrate_v3_to_v4(research_dir, dry_run, summary)
        ensure_v4_scaffolding(research_dir, dry_run, summary)
    elif layout == "v1":
        index_yaml_path = research_dir / "index.yaml"
        if not index_yaml_path.is_file():
            raise SystemExit(f"index.yaml not found in {research_dir}; not a research dir")
        migrate_v1_to_v4(research_dir, dry_run, summary)
        ensure_v4_scaffolding(research_dir, dry_run, summary)

    log_path = research_dir / "log.md"
    if not dry_run and layout != "v4":
        if layout == "v3":
            body = [
                f"- hoisted {len(summary.get('hoisted_from_memory', []))} entries from memory/ → root",
                "- removed empty memory/ wrapper",
            ]
            header = "layout v3 → v4"
        else:
            body = [
                f"- moved {len(summary.get('moved_files', []))} raw markdown file(s) into raw/",
                f"- moved {len(summary.get('moved_repo_dirs', []))} repo dir(s) into wiki/repos/",
                f"- repointed {summary.get('yaml', {}).get('repointed_uri_count', 0)} uri_* paths in index.yaml",
                "- created wiki/, raw/assets/ placeholders",
            ]
            header = "layout v1 → v4"
        append_log_entry(log_path, header, body)

    if not dry_run:
        summary["index_md"] = regenerate_index_md(research_dir)
    else:
        summary["index_md"] = "(dry-run: skipped index.md regeneration)"

    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--research-dir", required=True)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Plan the migration without moving files or writing.",
    )
    args = parser.parse_args()

    summary = migrate(Path(args.research_dir), dry_run=args.dry_run)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
